### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by wrabit** [Akryum/vue-progress-path#69]
on `npm install`

```
src/index.js → dist/vue-progress-path.min.js...
[!] (vue plugin) Error: Unknown transform 'collections'
src/components/Progress.vue
Error: Unknown transform 'collections'
    at error (vue-progress-path/node_modules/rollup/dist/rollup.js:185:14)
    at Promise.resolve.then.catch.err (vue-progress-path/node_modules/rollup/dist/rollup.js:9510:6)
```

**Comment by wrabit** [comment]
`yarn install` worked
